start_game:
  name: Start Game
  description: Start a new Soundbeats game session - resets teams and stops any countdown timer
  fields: {}

stop_game:
  name: Stop Game
  description: Stop the current Soundbeats game session
  fields: {}

reset_game:
  name: Reset Game
  description: Reset the Soundbeats game to initial state
  fields: {}

next_song:
  name: Next Song
  description: Skip to the next song and start the countdown timer
  fields: {}

update_team_name:
  name: Update Team Name
  description: Update the name of a team
  fields:
    team_id:
      name: Team ID
      description: The team identifier (team_1, team_2, team_3, team_4, or team_5)
      required: true
      example: "team_1"
      selector:
        text:
    name:
      name: Team Name
      description: The new name for the team
      required: true
      example: "Awesome Team"
      selector:
        text:

update_team_points:
  name: Update Team Points
  description: Update the points of a team
  fields:
    team_id:
      name: Team ID
      description: The team identifier (team_1, team_2, team_3, team_4, or team_5)
      required: true
      example: "team_1"
      selector:
        text:
    points:
      name: Points
      description: The new points value for the team
      required: true
      example: 100
      selector:
        number:
          min: 0
          max: 99999

update_team_participating:
  name: Update Team Participating
  description: Update whether a team is participating in the game
  fields:
    team_id:
      name: Team ID
      description: The team identifier (team_1, team_2, team_3, team_4, or team_5)
      required: true
      example: "team_1"
      selector:
        text:
    participating:
      name: Participating
      description: Whether the team is participating in the game
      required: true
      example: true
      selector:
        boolean:

update_countdown_timer_length:
  name: Update Countdown Timer Length
  description: Update the countdown timer length in seconds
  fields:
    timer_length:
      name: Timer Length
      description: The countdown timer length in seconds
      required: true
      example: 30
      selector:
        number:
          min: 5
          max: 300
          step: 5

update_audio_player:
  name: Update Audio Player
  description: Update the selected audio player for the game
  fields:
    audio_player:
      name: Audio Player
      description: The entity ID of the audio player to use
      required: true
      example: "media_player.living_room_speaker"
      selector:
        entity:
          domain: media_player

submit_team_guess:
  name: Submit Team Guess
  description: Submit a team's year guess for the current song
  fields:
    team_id:
      name: Team ID
      description: The team identifier (team_1, team_2, team_3, team_4, or team_5)
      required: true
      example: "team_1"
      selector:
        text:
    guessed_year:
      name: Guessed Year
      description: The year the team guesses for the current song
      required: true
      example: 1995
      selector:
        number:
          min: 1950
          max: 2030